gText_Birch_Welcome:: @ 82C897B
	.string "Come on you lazy grunt!\p"
	.string "We don't have all day!\p"
	.string "So you think you have what it takes to\n"
	.string "join Team Magma, do you?\p"
	.string "Time to stop lollygagging and listen up,\n"
	.string "grunt.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This POKéMON here”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This is your starter.\p"
	.string "Don't want a Poochyena? Tough luck.\p"
	.string "Maxie says Poochyena are to be the\n"
	.string "Magma standard starter.\p"
	.string "If you don't like it, find a different\n"
	.string "POKéMON.\p"
	.string "Personally, I could care less.\p"
	.string "This is a criminal organization, grunt.\n"
	.string "That means you can steal your own\l"
	.string "fucking POKéMON.\p"
	.string "Keep in mind that you can't steal from\n"
	.string "the people who support Team Magma.\l"
	.string "I assure you, Maxie and I will throw\l"
	.string "you out if you disobey that rule.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "What's your name?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "{PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Seriously? What a weird name.\n"
	.string "Whatever.\l"
	.string "Follow my instructions and you'll get\l"
	.string"your POKéMON.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "{PLAYER}{KUN}, go out there and stand with the\n"
	.string "rest of the grunts.\p"
	.string "And remember...\p"
	.string "What we do is for the good of Hoenn.\p"
	.string "$"
